apiVersion: v1
kind: Service
metadata:
  name: host-manager-svc-${release_label}
  labels:
    app: hostmanager-${release_label}
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: hostmanager-${release_label}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hostmanager--${release_label}
  labels:
    app: hostmanager-${release_label}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hostmanager-${release_label}
  template:
    metadata:
      labels:
        app: hostmanager-${release_label}
    spec:
      containers:
      - name: hostmanager-${release_label}
        image: ${image_name}
        ports:
        - containerPort: 80
